services:
  - type: web
    name: accessibility-scanner
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    healthCheckPath: /